---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: check-case-conflict
    - id: destroyed-symlinks
    - id: mixed-line-ending
    - id: check-byte-order-marker
    - id: check-added-large-files
    - id: check-shebang-scripts-are-executable
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.90.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yml
